### ISSUE TITLE
Move PyMunin3 to Munin Monitoring

### ISSUE THREAD

**Issue by penguinpee** [penguinpee/PyMunin3#5]
As suggested by @kenyon on IRC, let's move PyMunin3 to Munin Monitoring. Especially, if people come up with plugins based on PyMunin3, it feels like the natural habitat for this package.

Let's go and join the murder!

**Comment by penguinpee** [comment]
@steveschnepp, @sumpfralle, any thoughts? Kenyon deferred me to Steve or "someone else who is more active". I tried pinging Steve on IRC, but did not get any response.

**Comment by steveschnepp** [comment]
Standard way is to provide a PR to munin/contrib

**Comment by penguinpee** [comment]
I think the idea was to move the entire PyMunin3 repository into the munin-monitoring org, like munin-c or munin-lite. At least that's how I understood @kenyon, when he suggested that on IRC.

Maybe I misunderstood. In that case I could submit a PR for having a directory PyMunin3 with a README in there explaining how to install and use PyMunin3.

**Comment by steveschnepp** [comment]
oh. That's another option indeed. I usually don't like to have many repositories, but i guess it makes sense here...

That said I don't have a clue on how to so that...

**Comment by penguinpee** [comment]
It's in the Danger Zone :warning: How exciting.

![transfer_ownership](https://user-images.githubusercontent.com/98259694/197345246-f656d068-41b9-4135-a9be-5a935473910a.png)

I'll dig a little deeper. But looks like I can either transfer it to you and you setup the repo. Or you grant me contributor (?) access on munin-monitoring and I transfer it into a new munin-monitoring repo.

Based on current knowledge, I'd prefer the latter. Would need access anyway, since I'm still planning on maintaining and releasing.

**Comment by steveschnepp** [comment]
Ok. Let's do the following:
1. transfer it to me
2. I'll transfer it to the org
3. I'll grant you the access for maintaining that repo

As, I'm a little uneasy to grant you direct access to the org just now. Once we know each other better, sure!

**Comment by penguinpee** [comment]
I understand your concern regarding org access. I looked into the GitHub docs[^1] and think a direct transfer to the organization is the best option. It would, for instance, grant me collaborator access on the new repo in the org. I think that's the repo level access I need for maintenance.

I'm not entirely sure it will work, but I think if I give you sufficient access on the PyMunin3 repo, you should be able to transfer it directly into the org, without mee needing org access and without you needing to transfer it into your personal space first.

I'll start with making you contributor. I think that's the first step before granting further access. I don't see an option for making you admin or such straight away.

How does that plan sound?

[^1]: https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository

**Comment by steveschnepp** [comment]
Whatever works is fine with me 😉

**Comment by penguinpee** [comment]
Repo has been moved. URL changes have been committed, ready for next release. No immediate release required, since old URLs redirect properly.
